quotes_of_famous_people/quotes_of_famous_people/quotes/urls.py

from django.urls import path
from . import views

app_name = 'quotes'

urlpatterns = [
    path("", views.main, name="root"),
    path("<int:page>", views.main, name="root_paginate"),
    path("add_quote/", views.add_quote, name="add_quote"),
    path("add_author/", views.add_author, name="add_author"),
    path("author/<path:name>/", views.show_author, name="show_author"),
    path("quote_list/<path:name>/", views.find_quotes_by_tag, name="find_quotes_by_tag")
]

quotes_of_famous_people/quotes_of_famous_people/quotes_of_famous_people/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls")),

]

quotes_of_famous_people/quotes_of_famous_people/users/urls.py
from django.contrib.auth.views import (PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView
                                       )
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path("login/", views.loginuser, name="login"),
    path("logout/", views.logoutuser, name="logout"),
    path("registration/", views.registration, name="registration"),
    # path('profile/', views.profile, name='profile'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes_of_famous_people/quotes_of_famous_people/quotes/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField
from django.contrib.auth.models import User


# Create your models here.
class AuthorDjango(models.Model):
    fullname = models.CharField(max_length=10000, null=False, unique=True)
    born_date = models.CharField(max_length=10000)
    born_location = models.CharField(max_length=50000)
    description = models.CharField(max_length=10000)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=4)

    def __str__(self):
        return self.fullname


class QuoteDjango(models.Model):
    author = models.ForeignKey(AuthorDjango, on_delete=models.CASCADE,)
    tags = models.JSONField()
    quote = models.CharField(max_length=10000)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=4)

    def __str__(self):
        return f"Author:{self.author}, tags:{self.tags}, quote:{self.quote}"

quotes_of_famous_people/quotes_of_famous_people/quotes/forms.py
from django import forms
from .models import QuoteDjango, AuthorDjango


class AddQuote(forms.ModelForm):
    quote = forms.CharField(
        min_length=3, max_length=10000, required=True,
        widget=forms.TextInput(attrs={'id': 'quote'})
    )
    tags = forms.CharField(
        min_length=3, max_length=10000, required=True,
        widget=forms.TextInput(attrs={'id': 'tags'})
    )
    author = forms.ModelChoiceField(
        queryset=AuthorDjango.objects.all(), empty_label="Select author", required=True,
        widget=forms.Select(attrs={'id': 'author'})
    )

    class Meta:
        model = QuoteDjango
        fields = ['quote', 'tags', 'author']


class AddAuthor(forms.ModelForm):
    fullname = forms.CharField(
        min_length=3, max_length=50, required=True,
        widget=forms.TextInput(attrs={'id': 'fullname'})
    )
    born_date = forms.CharField(
        min_length=3, max_length=50,
        widget=forms.TextInput(attrs={'id': 'born_date'})
    )
    born_location = forms.CharField(
        min_length=3, max_length=50,
        widget=forms.TextInput(attrs={'id': 'born_location'})
    )
    description = forms.CharField(
        min_length=3, widget=forms.TextInput(attrs={'id': 'description'}))

    class Meta:
        model = AuthorDjango
        fields = ['fullname', 'born_date', 'born_location', 'description']

quotes_of_famous_people/quotes_of_famous_people/quotes/views.py
import re
from collections import Counter

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.core.paginator import Paginator

from .models import AuthorDjango, QuoteDjango
from .forms import AddQuote, AddAuthor


# Create your views here.
def main(request, page=1):
    quotes = QuoteDjango.objects.order_by('quote').all()
    quantity_page = 8
    paginator = Paginator(quotes, quantity_page)
    quotes_on_page = paginator.page(page)

    all_tags = QuoteDjango.objects.values_list('tags', flat=True)
    tag_counter = Counter()
    for tags in all_tags:
        for tag in tags:
            tag_counter[tag] += 1

    top_tags = [tag[0] for tag in tag_counter.most_common(10)]

    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page, 'top_tags': top_tags})


@login_required
def add_quote(request):
    if request.method == 'POST':
        form = AddQuote(request.POST)
        if form.is_valid():
            quote_data = form.cleaned_data
            tags_list = re.findall(r'\w+', quote_data['tags'])
            quote_data['tags'] = tags_list
            quote = QuoteDjango(**quote_data)
            quote.user = request.user
            quote.save()
            return redirect('quotes:root')
    else:
        form = AddQuote()
    return render(request, 'quotes/add_quote.html', {'form': AddQuote()})


@login_required
def add_author(request):
    if request.method == 'POST':
        form_author = AddAuthor(request.POST)
        if form_author.is_valid():
            add_user = form_author.save(commit=False)
            add_user.user = request.user
            add_user.save()
            return redirect('quotes:root')
    else:
        form_author = AddAuthor()
    return render(request, 'quotes/add_author.html', {'form_author': form_author})


def show_author(request, name):
    author = AuthorDjango.objects.get(fullname=name)
    return render(request, 'quotes/show_author.html', {'author': author})


def find_quotes_by_tag(request, name):
    founded_quotes = QuoteDjango.objects.filter(tags__contains=[name])
    return render(request, 'quotes/founded_quotes.html',
                  {'founded_quotes': founded_quotes, 'tag': name.capitalize()})

quotes_of_famous_people/quotes_of_famous_people/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}
{% block content %}

<div class="container mt-5" style="opacity: 0.8;">
    <div class="card">
        <div class="card-header">
            <h1 class="fst-italic">Add Author</h1>
        </div>
        <div class="card-body">
            <form method="POST" action="{% url 'quotes:add_author' %}">
                {% csrf_token %}
                <div class="mb-3">
                    <label class="fst-italic">Enter the fullname:</label>
                    {{ form_author.fullname }}
                    <div class="invalid-feedback">
                        {{ form_author.errors.fullname }}
                    </div>
                </div>
                <div class="mb-3">
                    <label class="fst-italic">Enter the born date:</label>
                    {{ form_author.born_date }}
                    <div class="invalid-feedback">
                        {{ form_author.errors.born_date }}
                    </div>
                </div>
                <div class="mb-3">
                    <label  class="fst-italic">Enter the born location:</label>
                    {{ form_author.born_location }}
                    <div class="invalid-feedback">
                        {{ form_author.errors.born_location }}
                    </div>
                </div>
                <div class="mb-3">
                    <label  class="fst-italic">Enter the description:</label>
                    {{ form_author.description }}
                    <div class="invalid-feedback">
                        {{ form_author.errors.description }}
                    </div>
                </div>
                <div class="d-flex justify-content-between">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <button type="reset" class="btn btn-secondary">Reset</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

quotes_of_famous_people/quotes_of_famous_people/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}
{% block content %}


<div class="container mt-5" style="opacity: 0.8;">
    <div class="card">
        <div class="card-header">
            <h2 class="fst-italic">Add a Quote</h2>
        </div>
        <div class="card-body">
            <form method="POST" action="{% url 'quotes:add_quote' %}">
                {% csrf_token %}
                <div class="mb-3">
                    <label class="fst-italic">Enter the quote:</label>
                    {{ form.quote }}
                </div>
                <div class="mb-3">
                    <label class="fst-italic">Select the author:</label>
                    {{ form.author }}
                </div>
                <div class="mb-3">
                    <label  class="fst-italic">Enter the tags:</label>
                    {{ form.tags }}
                </div>
                <div class="d-flex justify-content-between">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <button type="reset" class="btn btn-secondary">Reset</button>
                </div>
            </form>
        </div>
    </div>
</div>


 {% endblock %}

quotes_of_famous_people/quotes_of_famous_people/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% csrf_token %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Main Page</title>

</head>
<body id="bg" style="background-image: url('{% static "quotes/images/background.png" %}');">
<nav class="navbar bg-body-tertiary justify-content-between" style="opacity: 0.7;">
    {% if user.is_authenticated %}
    <div>
        <a href="{% url 'quotes:add_quote' %}" class="btn btn-warning" type="button">Add quote</a>
        <a href="{% url 'quotes:add_author' %}" class="btn btn-warning" type="button">Add author</a>
        <a href="{% url 'quotes:root' %}" class="btn btn-info" type="button">Main</a>
    </div>
    <div class="d-flex align-items-center">
        <span style="margin-right: 60px;">Welcome <b>{{ user.username }}!</b></span>
        <a href="{% url 'users:logout' %}" class="btn btn-light" type="button">Logout</a>
    </div>
    {% else %}
    <div>
        <a href="{% url 'quotes:root' %}" class="btn btn-info" type="button">Main</a>
    </div>
    <div>
        <a href="{% url 'users:login' %}" class="btn btn-success" type="button">Login</a>
        <a href="{% url 'users:registration' %}" class="btn btn-outline-secondary" type="button">Registration</a>
    </div>
    {% endif %}
</nav>
<div class="container">


    {% block content %}
    {% endblock %}


</div>

</body>
</html>

quotes_of_famous_people/quotes_of_famous_people/quotes/templates/quotes/founded_quotes.html
{% extends 'quotes/base.html' %}
{% block content %}
 <div class="col-md-8">
        <h1>
            <a href="/" style="text-decoration: none"><u>{{tag}}</u></a>
        </h1>
    </div>
{% for quote in founded_quotes %}
<div class="row">
    <div class="col-md-8">
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
        <a href="{% url 'quotes:show_author' quote.author %}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags %}
                <a class="tag" href="{% url 'quotes:find_quotes_by_tag' tag %}">{{tag}}</a>
                {%endfor%}
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

quotes_of_famous_people/quotes_of_famous_people/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% block content %}

<div class="row header-box pt-3 mb-3">
    <div class="col-md-8">
        <h1>
            <a href="/" style="text-decoration: none">Quotes of famous people</a>
        </h1>
    </div>
</div>

<div class="row">
    <div class="col-md-8">
        <!-- Quotes content -->
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
                <a href="{% url 'quotes:show_author' quote.author %}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags %}
                <a class="tag" href="{% url 'quotes:find_quotes_by_tag' tag %}">{{tag}}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}

        <!-- Pagination -->
        <nav aria-label="Page navigation example">
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <! Previous page button>
                    <li class="{% if not quotes.has_previous %} page-item disabled {% else %} page-item {% endif %}">
                        <a class="page-link"
                           href="{% if quotes.has_previous%} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">Previous</a>
                    </li>
                    <! Number previous button>
                    {% if quotes.has_previous %}
                    <li class="page-item"><a
                            class="page-link"
                            href="{% url 'quotes:root_paginate' quotes.previous_page_number %}">{{quotes.previous_page_number}}</a>
                    </li>
                    {% endif %}
                    <! Currently page number>
                    <li class="page-item active"><a class="page-link"
                                                    href="{% url 'quotes:root_paginate' quotes.number %}">{{quotes.number}}</a>
                    </li>
                    <!Next page number button>
                    {% if quotes.has_next %}
                    <li class="page-item "><a class="page-link"
                                              href="{% if quotes.has_next%} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">{{quotes.next_page_number}}</a>
                    </li>
                    {% endif %}
                    <!Next page button>
                    <li class="{% if not quotes.has_next %} page-item disabled {% else %} page-item {% endif %}">
                        <a class="page-link"
                           href="{% if quotes.has_next%} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">Next</a>
                    </li>
                </ul>
            </nav>
        </nav>
    </div>

    <!-- New column for tags -->
    <div class="col-md-4 tags-box">
        <h2>Top Ten tags</h2>
        <!-- Tags content -->
        {% for top_tag in top_tags %}
        <span class="tag-item" style="display: block;">
        <a class="tag-top10" style="font-size: 24px;" href="{% url 'quotes:find_quotes_by_tag' top_tag %}">{{ forloop.counter }}. {{top_tag}}</a>
    </span>

        {% endfor %}
    </div>
</div>

{% endblock %}

quotes_of_famous_people/quotes_of_famous_people/quotes/templates/quotes/show_author.html
{% extends 'quotes/base.html' %}
{% block content %}

<div class="container">


    <div >
        <h3 class="fw-light">{{author.fullname}}</h3>
        <p><strong>Born:</strong> <span class="fw-semibold">{{author.born_date}}</span>
            <span class="fw-semibold">{{author.born_location}}</span></p>
        <p ><strong>Description:</strong></p>
        <div class="fst-italic" style="font-size: 20px;">
            {{author.description}}
        </div>
    </div>

</div>
{% endblock %}
