quotes_of_famous_people/quotes_of_famous_people/quotes_of_famous_people/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls")),

]

quotes_of_famous_people/quotes_of_famous_people/users/urls.py
from django.contrib.auth.views import (PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView
                                       )
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path("login/", views.loginuser, name="login"),
    path("logout/", views.logoutuser, name="logout"),
    path("registration/", views.registration, name="registration"),
    # path('profile/', views.profile, name='profile'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes_of_famous_people/quotes_of_famous_people/users/models.py
from django.db import models

# Create your models here.

quotes_of_famous_people/quotes_of_famous_people/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User



class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())
    email = forms.EmailField(max_length=50,
                             required=True,
                             widget=forms.EmailInput())
    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']


# class ProfileForm(forms.ModelForm):
#     avatar = forms.ImageField(widget=forms.FileInput())
#
#     class Meta:
#         model = Profile
#         fields = ['avatar']



quotes_of_famous_people/quotes_of_famous_people/users/views.py
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_protect

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin

from .forms import RegisterForm, LoginForm


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'


# Create your views here.
@csrf_protect
def registration(request):
    if request.user.is_authenticated:
        return redirect(to='quotes:root')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'users/registration.html', context={"reg_form": form})
    return render(request, 'users/registration.html', {'reg_form': RegisterForm()})


@csrf_protect
def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotes:root')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quotes:root')

    return render(request, 'users/login.html', context={"login_form": LoginForm()})


@csrf_protect
@login_required
def logoutuser(request):
    logout(request)
    return redirect('quotes:root')

quotes_of_famous_people/quotes_of_famous_people/users/templates/users/login.html
{% extends 'quotes/base.html' %}
{% block content %}
<div class="container mt-5">
    <div class="row header-box pt-3 mb-3">
        <div class="col-md-8">
            <h1>
                <span class="registration-link" style="color: green;">Login</span>
            </h1>
        </div>
    </div>

    {% if messages %}
    <div class="mb-3">
        {% for message in messages %}
        <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}

    <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username:</label>
            {{ login_form.username }}
        </div>

        <div class="mb-3">
            <label class="form-label">Password:</label>
            {{ login_form.password }}
        </div>

        <div class="d-flex justify-content-between ">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
            <a href="{% url 'users:password_reset' %}" class="btn btn-info" type="button">Forgot Password?</a>
        </div>
        <div class="small text-center">

        </div>
    </form>
</div>

{% endblock %}


quotes_of_famous_people/quotes_of_famous_people/users/templates/users/password_reset.html
{% extends 'quotes/base.html' %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

quotes_of_famous_people/quotes_of_famous_people/users/templates/users/password_reset_complete.html
{% extends 'quotes/base.html' %}

{% block content %}

<h2>{{name}}</h2>
<div>
    <a href="{% url 'users:login' %}" class="btn btn-success" type="button">Login</a>

</div>

{% endblock %}

quotes_of_famous_people/quotes_of_famous_people/users/templates/users/password_reset_confirm.html
{% extends 'quotes/base.html' %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

quotes_of_famous_people/quotes_of_famous_people/users/templates/users/password_reset_done.html
{% extends 'quotes/base.html' %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

quotes_of_famous_people/quotes_of_famous_people/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

quotes_of_famous_people/quotes_of_famous_people/users/templates/users/registration.html
{% extends 'quotes/base.html' %}
{% block content %}

<div class="container mt-5">
    <div class="row header-box pt-3 mb-3">
        <div class="col-md-8">
            <h1>
                <span >Registration</span>
            </h1>
        </div>
    </div>

    {% if messages %}
    <div class="mb-3">
        {% for message in messages %}
        <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}

    <form method="post" action="{% url 'users:registration' %}">
        {% csrf_token %}
        <div class="mb-3">
            <label  class="form-label">Username:</label>
            {{ reg_form.username }}
            <div class="invalid-feedback">
                {{ reg_form.errors.username }}
            </div>
        </div>
        <div class="mb-3">
            <label  class="form-label">Email:</label>
            {{ reg_form.email }}
            <div class="invalid-feedback">
                {{ reg_form.errors.email }}
            </div>
        </div>
        <div class="mb-3">
            <label  class="form-label">Password:</label>
            {{ reg_form.password1 }}
            <div class="invalid-feedback">
                {{ reg_form.errors.password1 }}
            </div>
        </div>
        <div class="mb-3">
            <label  class="form-label">Password confirmation:</label>
            {{ reg_form.password2 }}
            <div class="invalid-feedback">
                {{ reg_form.errors.password2 }}
            </div>
        </div>
        <div class="d-flex justify-content-between">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </form>
</div>

{% endblock %}